version: '3.2'
services:
    ugs-api:
        container_name: "ugs-api"
        image: "thejinchao/ugs-python:latest"
        restart: always
        environment:
            - UGS_LISTEN_PORT: "5001"
            - DB_UGS_HOST=${DB_UGS_HOST}
            - DB_UGS_PORT=${DB_UGS_PORT}
            - DB_UGS_USERNAME=${DB_UGS_USERNAME}
            - DB_UGS_PASSWORD=${DB_UGS_PASSWORD}
            - DB_UGS_DBNAME=${DB_UGS_DBNAME}
            - DB_UGS_CHARSET=${DB_UGS_CHARSET}
        ports:
            - 5001:5001


